### ISSUE TITLE
Readme 

### ISSUE THREAD

**Issue by AndreasRoither** [Folling/exprust#1]
Damn you need a better readme 😄 

Like so:
[VS-LaTeX-Include](https://github.com/AndiRoither/VS-LaTexInclude)  
# VS-LaTeX-Include

### What it does:

VS-LaTeX-Include generates a .tex file containing stylized content based on different file types (Code, Images, PDF,...) from a folder.
You can customize the output .tex according to your needs.
* Change Title, Date and other basic inormation
* Add Sections and subsections
* Change the order of your listed files

#### Example
Say you want to include different files in different folders in a .tex file.
<p align="left">
  <img src="images/example_folderstructure.png" width="200"/>
</p>

VS-LaTeX-Include does the job for you so you don't have to worry about those pesky path declerations.

### Installation
[VS-LaTeX-Include release](https://github.com/AndiRoither/VS-LaTexInclude/releases)  

### How to use
Place the executable wherever you desire and run it.

### INFO
There is a possibility to register the .exe in the registry. This allows you to use LaTexInclude via the context menu (right click on a file or a folder) and start LaTexInclude with the file(s) in its List. If you uncheck the "Start with context" setting under "Settings -> General" an output.tex file will be generated in the folder you are in.

In order to add the context menu item you need to do the following:  

- Start the .exe as administrator
- Go to settings -> advanced
- Click one of the buttons (File/Folder)
- Enjoy

### Technology used
Built with [Visual Studio](https://www.visualstudio.com/downloads/)

#### Framework:
* MVVM Light Toolkit

#### Nuggets:
* Install-Package WindowsAPICodePack-Core
* Install-Package WindowsAPICodePack-ExtendedLinguisticServices
* Install-Package WindowsAPICodePack-Sensors
* Install-Package WindowsAPICodePack-Shell
* Install-Package WindowsAPICodePack-ShellExtensions
* Install-Package Extended.Wpf.Toolkit
* Install-Package Costura.Fody
* Install-CleanReferencesTarget

#### UI Framework MahApps Metro:
* Install-Package MahApps.Metro

**Comment by Folling** [comment]
Hey Andy, this is a WIP
I wanted to get all the basic functionality done before moving on to actually making things proper.
The code's neither commented yet, nor is there any proper file-system.
My next step, after flags, will be to implement those right next to a documentation and a read-me for this project.

**Comment by AndreasRoither** [comment]
Oh nice, well be sure to make use of the markdown if you write a readme for this, it's pretty neat. You should also use the issues more, for example assigning labels to an issue (bug, in progress) or sth like that. If you are working alone it's fine if you don't use it but it's nice to have/use. Pretty nice that you write stuff in rust, how is it?

**Comment by Folling** [comment]
I have waffle.io or gitlab for these kind of things :D 
Rust is absolutely amazing. It takes a bit of time to get used to since it behaves fundamentally different than most other languages but it's gorgeous once you get into it.

**Comment by sn0w** [comment]
👀

**Comment by sn0w** [comment]
👀

**Comment by ghost** [comment]
👍
